In [20]:
import pandas as pd
# read file
df = pd.read_csv('BreakfastFiestaOrderLog.csv', usecols = ['Cliente', 'Orden', 'Delivery Address'], index_col='Cliente')

# remove all orders that will be picked up
df = df[~df['Delivery Address'].isin(['Pickup'])]

# drop blank cells
df = df.dropna()

df = df.head(22)

df

,Orden,Delivery Address
Cliente,,
Dayanis_10,Combo #7,"19341 NW 48th Ct, Miami Gardens, FL 33055"
Wabyy_,Combo #4,"5000 W 12th Ct Apt 5, Hialeah, FL 33012"
Wabyy_,Combo #4,"18006 NW 24th Pl, Pembroke Pines, FL 33029"
eliiizabeth.__,Arreglo de globos,"15900 SW 144th Ct, Miami, FL 33177"
betsy4513,Multiple (vea notas),"2470 SE 14th Ct, Homestead, FL 33035"
kevg305,Combo #5,"8461 Dundee Terrace, Miami Lakes, FL 33016"
_Wilson_world,Combo #2,"11519 SW 236th St, Homestead, FL 33032"
Drey_uhhh,Combo #3,"11790 SW 35th Ter, Miami, FL 33175"
Drey_uhhh,Combo #3,"12732 SW 68th Ter, Miami, FL 33183"
Melisa,Combo #5,"5790 W 13 Ct, Hialeah, FL 33012"
Melisa,Combo #5,"8423 NW 138th Ter Unit 2801, Miami Lakes, FL 3..."
Chave1496,Combo #2,"2150 NW 23rd Ct Apt 4A, Miami, FL 33142"
Denise Nunez,Combo #5,"460 E 36th St, Hialeah, FL 33013"
Monika Client,Combo #3,"17620 NW 78rd Ave Apt 200, Hialeah, FL 33015"
Cindy_x98,Combo #5,"11485 SW 49th Ter, Miami, FL 33165"
Cindy_x98,Combo #5,"15384 SW 169th Ln, Miami, FL 33187"
Mily Client,Combo #3,"242 W 38th St, Hialeah, FL 33012"
Claudiadaamn,Combo #5,"2211 W 52nd St Apt 206, Hialeah, FL 33016"
el_pitynq,Combo #5 w/ champagne,"14855 SW 57th Ln Apt 12, Miami, FL 33183"
Imi_rguez,Combo #7,"1714 W 72nd St, Hialeah, FL 33014"
valenmachp,Combo #4,"6238 NW 171st St, Hialeah, FL 33015"
Omayrarod_03,Combo #7,"5109 SW 5th St, Miami, FL 33134"