In [22]:
import pandas as pd

# read file
df = pd.read_csv('BreakfastFiestaOrderLog_latlong.csv', usecols = ['Cliente', 'Orden', 'Delivery Address', 'Latitude', 'Longitude'], index_col='Cliente')

# remove all orders that will be picked up
df = df[~df['Delivery Address'].isin(['Pickup'])]

# drop blank cells
df = df.dropna()

df = df.head(22)

df

,Orden,Delivery Address,Latitude,Longitude
Cliente,,,,
Dayanis_10,Combo #7,"19341 NW 48th Ct, Miami Gardens, FL 33055",25.949633,-80.280748
Wabyy_,Combo #4,"5000 W 12th Ct Apt 5, Hialeah, FL 33012",25.867947,-80.307920
Wabyy_,Combo #4,"18006 NW 24th Pl, Pembroke Pines, FL 33029",25.986615,-80.389558
eliiizabeth.__,Arreglo de globos,"15900 SW 144th Ct, Miami, FL 33177",25.619406,-80.427357
betsy4513,Multiple (vea notas),"2470 SE 14th Ct, Homestead, FL 33035",25.455880,-80.439480
kevg305,Combo #5,"8461 Dundee Terrace, Miami Lakes, FL 33016",25.909754,-80.337282
_Wilson_world,Combo #2,"11519 SW 236th St, Homestead, FL 33032",25.548208,-80.378468
Drey_uhhh,Combo #3,"11790 SW 35th Ter, Miami, FL 33175",25.735550,-80.385851
Drey_uhhh,Combo #3,"12732 SW 68th Ter, Miami, FL 33183",25.702964,-80.399806
Melisa,Combo #5,"5790 W 13 Ct, Hialeah, FL 33012",25.875042,-80.310713
Melisa,Combo #5,"8423 NW 138th Ter Unit 2801, Miami Lakes, FL 3...",25.899725,-80.337944
Chave1496,Combo #2,"2150 NW 23rd Ct Apt 4A, Miami, FL 33142",25.796535,-80.234819
Denise Nunez,Combo #5,"460 E 36th St, Hialeah, FL 33013",25.854878,-80.273396
Monika Client,Combo #3,"17620 NW 78rd Ave Apt 200, Hialeah, FL 33015",25.933772,-80.327272
Cindy_x98,Combo #5,"11485 SW 49th Ter, Miami, FL 33165",25.721073,-80.381112
Cindy_x98,Combo #5,"15384 SW 169th Ln, Miami, FL 33187",25.609076,-80.441792
Mily Client,Combo #3,"242 W 38th St, Hialeah, FL 33012",25.856330,-80.287508
Claudiadaamn,Combo #5,"2211 W 52nd St Apt 206, Hialeah, FL 33016",25.870162,-80.327160
el_pitynq,Combo #5 w/ champagne,"14855 SW 57th Ln Apt 12, Miami, FL 33183",25.712640,-80.432032
Imi_rguez,Combo #7,"1714 W 72nd St, Hialeah, FL 33014",25.887652,-80.318098
valenmachp,Combo #4,"6238 NW 171st St, Hialeah, FL 33015",25.929102,-80.304068
Omayrarod_03,Combo #7,"5109 SW 5th St, Miami, FL 33134",25.767088,-80.277471

In [30]:
import pandas as pd
import gmaps
from datetime import datetime
from ipywidgets.embed import embed_minimal_html
apikey = 'AIzaSyAdzwCpBzLDrhbtsZbFUDNKPJA0zIpshic'
now = datetime.now()


start = (25.86313861266461, -80.247161730114)
end = start


# read file
df = pd.read_csv('BreakfastFiestaOrderLog_latlong.csv', usecols = ['Cliente', 'Orden', 'Delivery Address', 'Latitude', 'Longitude'], index_col='Cliente')

# remove all orders that will be picked up
df = df[~df['Delivery Address'].isin(['Pickup'])]

# drop blank cells
df = df.dropna()

df = df.head(22)



waypoints = list(zip(df['Latitude'],df['Longitude']))

gmaps.configure(api_key=apikey)

fig = gmaps.figure()

layer = gmaps.directions.Directions(start, end, waypoints = waypoints, optimize_waypoints=True, mode='car', api_key=apikey, departure_time=now)

fig.add_layer(layer)
fig

embed_minimal_html('export.html', views=[fig])